# Generated by Django 5.2.6 on 2025-10-12 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grounds', '0003_remove_ground_address_remove_ground_lat_and_more'),
        ('matches', '0009_delete_featuredimage_alter_challenge_challenger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('total_runs_scored', models.PositiveIntegerField(default=0)),
                ('total_wickets', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('highest_score', models.PositiveIntegerField(default=0)),
                ('lowest_score', models.PositiveIntegerField(default=0)),
                ('batting_friendly_rating', models.FloatField(default=0.0)),
                ('bowling_friendly_rating', models.FloatField(default=0.0)),
                ('overall_rating', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ground', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_stats', to='grounds.ground')),
            ],
            options={
                'verbose_name': 'Ground Statistics',
                'verbose_name_plural': 'Ground Statistics',
            },
        ),
        migrations.CreateModel(
            name='MatchStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_scored', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('batting_average', models.FloatField(default=0.0)),
                ('overs_bowled', models.FloatField(default=0.0)),
                ('runs_conceded', models.PositiveIntegerField(default=0)),
                ('wickets_taken', models.PositiveIntegerField(default=0)),
                ('maidens', models.PositiveIntegerField(default=0)),
                ('bowling_average', models.FloatField(default=0.0)),
                ('economy_rate', models.FloatField(default=0.0)),
                ('bowling_strike_rate', models.FloatField(default=0.0)),
                ('catches', models.PositiveIntegerField(default=0)),
                ('stumpings', models.PositiveIntegerField(default=0)),
                ('run_outs', models.PositiveIntegerField(default=0)),
                ('match_date', models.DateTimeField()),
                ('result', models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('DRAW', 'Draw'), ('TIE', 'Tie')], max_length=10)),
                ('performance_rating', models.FloatField(default=0.0)),
                ('contribution_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ground', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grounds.ground')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='matches.challenge')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_stats', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match Statistics',
                'verbose_name_plural': 'Match Statistics',
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_wickets', models.PositiveIntegerField(default=0)),
                ('total_catches', models.PositiveIntegerField(default=0)),
                ('total_stumpings', models.PositiveIntegerField(default=0)),
                ('total_run_outs', models.PositiveIntegerField(default=0)),
                ('career_batting_average', models.FloatField(default=0.0)),
                ('career_strike_rate', models.FloatField(default=0.0)),
                ('highest_score', models.PositiveIntegerField(default=0)),
                ('total_fours', models.PositiveIntegerField(default=0)),
                ('total_sixes', models.PositiveIntegerField(default=0)),
                ('total_balls_faced', models.PositiveIntegerField(default=0)),
                ('career_bowling_average', models.FloatField(default=0.0)),
                ('career_economy_rate', models.FloatField(default=0.0)),
                ('career_bowling_strike_rate', models.FloatField(default=0.0)),
                ('best_bowling_figures', models.CharField(blank=True, max_length=20)),
                ('total_overs_bowled', models.FloatField(default=0.0)),
                ('total_runs_conceded', models.PositiveIntegerField(default=0)),
                ('total_maidens', models.PositiveIntegerField(default=0)),
                ('win_percentage', models.FloatField(default=0.0)),
                ('contribution_rating', models.FloatField(default=0.0)),
                ('consistency_rating', models.FloatField(default=0.0)),
                ('recent_form_rating', models.FloatField(default=0.0)),
                ('recent_batting_average', models.FloatField(default=0.0)),
                ('recent_bowling_average', models.FloatField(default=0.0)),
                ('batting_rank', models.PositiveIntegerField(default=0)),
                ('bowling_rank', models.PositiveIntegerField(default=0)),
                ('all_rounder_rank', models.PositiveIntegerField(default=0)),
                ('overall_rank', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player Statistics',
                'verbose_name_plural': 'Player Statistics',
                'ordering': ['-overall_rank'],
            },
        ),
        migrations.CreateModel(
            name='SeasonStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('total_players', models.PositiveIntegerField(default=0)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_wickets', models.PositiveIntegerField(default=0)),
                ('highest_individual_score', models.PositiveIntegerField(default=0)),
                ('best_bowling_figures', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('most_runs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_most_runs', to=settings.AUTH_USER_MODEL)),
                ('most_wickets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_most_wickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Season Statistics',
                'verbose_name_plural': 'Season Statistics',
                'ordering': ['-start_date'],
            },
        ),
    ]
