# Generated by Django 5.2.6 on 2025-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='address',
            field=models.CharField(blank=True, help_text='Full address of the ground', max_length=300),
        ),
        migrations.AddField(
            model_name='ground',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
    ]
