# Generated by Django 5.2.6 on 2025-10-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0002_ground_address_ground_lat_ground_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ground',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='lng',
        ),
    ]
