# Generated by Django 5.2.6 on 2025-10-05 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary for preview', max_length=500),
        ),
        migrations.AddField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the article', null=True, upload_to='news/images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(help_text='Full article content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False, help_text='Publish this article'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this article was published', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='News article title', max_length=200),
        ),
    ]
