# Generated by Django 5.2.6 on 2025-10-05 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balls_bowled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balls_faced',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matches_played',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matches_won',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='runs_scored',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wickets_taken',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Tampere', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_batting_style',
            field=models.CharField(blank=True, choices=[('right_handed', 'Right Handed'), ('left_handed', 'Left Handed')], help_text='Your batting style', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_bowling_style',
            field=models.CharField(blank=True, choices=[('right_arm_fast', 'Right Arm Fast'), ('right_arm_medium', 'Right Arm Medium'), ('right_arm_spin', 'Right Arm Spin'), ('left_arm_fast', 'Left Arm Fast'), ('left_arm_medium', 'Left Arm Medium'), ('left_arm_spin', 'Left Arm Spin'), ('leg_spin', 'Leg Spin'), ('off_spin', 'Off Spin')], help_text='Your bowling style', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('batter', 'Batter'), ('bowler', 'Bowler'), ('allrounder', 'All Rounder')], default='allrounder', help_text='Your primary role in cricket', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='years_playing',
            field=models.PositiveIntegerField(default=0, help_text='Years of cricket experience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Tell us about your cricket experience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='intermediate', help_text='Your cricket experience level', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=1000.0)),
                ('batting_rating', models.FloatField(default=1000.0)),
                ('bowling_rating', models.FloatField(default=1000.0)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('balls_bowled', models.PositiveIntegerField(default=0)),
                ('fcm_token', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
