# Generated by Django 5.2.6 on 2025-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_balls_bowled_remove_user_balls_faced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_batting_rank',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_bowling_rank',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_overall_rank',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ranking_change_batting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ranking_change_bowling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ranking_change_overall',
            field=models.IntegerField(default=0),
        ),
    ]
