# Generated by Django 5.2.6 on 2025-10-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_previous_batting_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the user was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_reason',
            field=models.TextField(blank=True, help_text='Reason for deletion'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
