# Generated by Django 5.2.6 on 2025-10-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_deleted_at_user_deleted_reason_user_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='years_playing',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('batter', 'Batter'), ('bowler', 'Bowler'), ('allrounder', 'All Rounder')], default='allrounder', help_text='Your primary role in cricket', max_length=10),
        ),
    ]
