# Generated by Django 5.2.6 on 2025-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_unused_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batting_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bowling_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
