# Generated by Django 5.2.6 on 2025-10-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='matric',
            field=models.CharField(blank=True, help_text="Challenge metric (e.g., 'Runs', 'Wickets', 'Sixes')", max_length=100),
        ),
        migrations.AddField(
            model_name='challenge',
            name='over',
            field=models.PositiveIntegerField(blank=True, help_text='Number of overs for the challenge', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='values',
            field=models.PositiveIntegerField(blank=True, help_text='Target value for the metric', null=True),
        ),
    ]
