# Generated by Django 5.2.6 on 2025-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_challenge_matric_challenge_over_challenge_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='matric',
            new_name='metric',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='values',
            new_name='target_value',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='over',
            new_name='over_count',
        ),
        migrations.AddField(
            model_name='challenge',
            name='summary',
            field=models.TextField(blank=True, help_text='Additional comments or summary'),
        ),
    ]
