# Generated by Django 5.2.6 on 2025-10-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20251005_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='duration',
            field=models.PositiveIntegerField(default=15, help_text='Duration in minutes'),
        ),
    ]
