# Generated by Django 5.2.6 on 2025-10-05 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_challenge_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger_runs', models.PositiveIntegerField(default=0, help_text='Runs scored by challenger')),
                ('challenger_wickets', models.PositiveIntegerField(default=0, help_text='Wickets taken by challenger')),
                ('challenger_sixes', models.PositiveIntegerField(default=0, help_text='Sixes hit by challenger')),
                ('challenger_fours', models.PositiveIntegerField(default=0, help_text='Fours hit by challenger')),
                ('challenger_dots', models.PositiveIntegerField(default=0, help_text='Dot balls bowled by challenger')),
                ('opponent_runs', models.PositiveIntegerField(default=0, help_text='Runs scored by opponent')),
                ('opponent_wickets', models.PositiveIntegerField(default=0, help_text='Wickets taken by opponent')),
                ('opponent_sixes', models.PositiveIntegerField(default=0, help_text='Sixes hit by opponent')),
                ('opponent_fours', models.PositiveIntegerField(default=0, help_text='Fours hit by opponent')),
                ('opponent_dots', models.PositiveIntegerField(default=0, help_text='Dot balls bowled by opponent')),
                ('total_overs', models.PositiveIntegerField(default=0, help_text='Total overs played')),
                ('match_duration', models.PositiveIntegerField(default=0, help_text='Match duration in minutes')),
                ('weather_conditions', models.CharField(blank=True, help_text='Weather conditions during match', max_length=100)),
                ('pitch_conditions', models.CharField(blank=True, help_text='Pitch conditions', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional match notes or comments')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_result', to='matches.challenge')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match Result',
                'verbose_name_plural': 'Match Results',
            },
        ),
    ]
