# Generated by Django 5.2.6 on 2025-10-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_challenge_team1_batter_challenge_team1_bowler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='team1_batter_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='team1_bowler_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='team2_batter_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='team2_bowler_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
