# Generated by Django 5.2.6 on 2025-10-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_challenge_team1_batter_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the featured image', max_length=200)),
                ('image', models.ImageField(help_text='Featured image to display', upload_to='featured_images/')),
                ('description', models.TextField(blank=True, help_text='Optional description of the featured content')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Featured Image',
                'verbose_name_plural': 'Featured Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
