# Generated by Django 5.2.6 on 2025-10-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_delete_featuredimage_alter_challenge_challenger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=15, help_text='Duration in minutes'),
        ),
    ]
